# ========================
# Spring Datasource Config
# ========================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ========================
# JPA / Hibernate Config
# ========================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# ========================
# Servlet Multipart Config
# ========================
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ========================
# Server Config
# ========================
server.port=${PORT:8080}

# ========================
# Application Custom Config
# ========================
application.api.key=${APP_KEY}

jwt.secret.key=${JWT_SECRET}

pos_sales_id=${MERCHANT_ID}
client_id=${CLIENT_ID}
client_secret=${CLIENT_SECRET}
sms_client_id=${SMS_CLIENT_ID}
sms_client_secret=${SMS_CLIENT_SECRET}
hubtel_secrety_key=${HUBTEL_SECRET_KEY}
callback_url=${CALLBACK_URL}
cancellation_url=${CANCELLATION_URL}
return_url=${RETURN_URL}
redde_online_api_key=${REDDE_KEY}
redde_online_app_id=${REDDE_APP_ID}
logo_url=

# ========================
# Proxy Config
# ========================
proxy.server.host=${PROXY_HOST}
proxy.server.port=${PROXY_PORT}
proxy.server.username=${PROXY_USERNAME}
proxy.server.password=${PROXY_PASSWORD}

# ========================
# Logging Levels
# ========================
logging.level.org.springframework.security.access.intercept=DEBUG
logging.level.org.springframework.security.access.prepost=DEBUG

springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
