spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
  
application:
  api:
    key: ${APP_KEY}

jwt:
  secret:
    key: ${JWT_SECRET}

pos_sales_id: ${MERCHANT_ID}
client_id: ${CLIENT_ID}
client_secret: ${CLIENT_SECRET}
sms_client_id: ${SMS_CLIENT_ID}
sms_client_secret: ${SMS_CLIENT_SECRET}
hubtel_secrety_key: ${HUBTEL_SECRET_KEY}
callback_url: ${CALLBACK_URL}
cancellation_url: ${CANCELLATION_URL}
return_url: ${RETURN_URL}
redde_online_api_key: ${REDDE_KEY}
redde_online_app_id: ${REDDE_APP_ID}
logo_url: 

proxy:
  server:
    host: ${PROXY_HOST}
    port: ${PROXY_PORT}
    username: ${PROXY_USERNAME}
    password: ${PROXY_PASSWORD}

